# Copyright (c) 2022 github.com/System233
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT
name: Build

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        android_abi: [armeabi-v7a,arm64-v8a,x86,x86_64]
        android_platform: [20,19]
        type: [shared,static]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Build
        id: build
        run: |
          ANDROID_ABI=${{matrix.android_abi}}
          ANDROID_PLATFORM=${{matrix.android_platform}}
          BUILD_TYPE=${{matrix.type}}
          BOOST_VERSION=$(./latest-boost-version.sh)
          ICU_VERSION=$(./latest-icu-version.sh)
          ICU_NAME=$(echo $ICU_VERSION|grep --perl-regex -e "release-\\K(.*)"  --only-matching|sed -e "s/-/./g")

          ANDROID_ABI_NO_HYPHEN=$(echo $ANDROID_ABI | sed 's/-//g')
          BOOST_DIST_NAME=$BOOST_VERSION-icu$ICU_NAME-android$ANDROID_PLATFORM-$ANDROID_ABI_NO_HYPHEN-$BUILD_TYPE
          
          echo "BOOST_VERSION=$BOOST_VERSION" >> $GITHUB_OUTPUT
          echo "ICU_VERSION=$ICU_VERSION" >> $GITHUB_OUTPUT
          echo "TAG_NAME=$BOOST_VERSION-icu$ICU_NAME" >> $GITHUB_OUTPUT
          echo "DIST_NAME=$BOOST_DIST_NAME" >> $GITHUB_OUTPUT
          echo $BOOST_VERSION-$ICU_VERSION-$BUILD_TYPE

          echo BOOST_VERSION=$BOOST_VERSION
          echo ICU_VERSION=$ICU_NAME/$ICU_VERSION
          echo BUILD_OUTPUT=$BOOST_DIST_NAME

          ./build.sh $ANDROID_ABI $ANDROID_PLATFORM $BOOST_VERSION $ICU_VERSION $BUILD_TYPE
      - name: Archive
        run: |
          cd dist
          zip -9 ../${{steps.build.outputs.DIST_NAME}}.zip -r . 
          tar -czf ../${{steps.build.outputs.DIST_NAME}}.tar.gz .
          cd ..
          sha1sum ${{steps.build.outputs.DIST_NAME}}.zip >${{steps.build.outputs.DIST_NAME}}.zip.sha1
          sha1sum ${{steps.build.outputs.DIST_NAME}}.tar.gz >${{steps.build.outputs.DIST_NAME}}.tar.gz.sha1
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{steps.build.outputs.TAG_NAME}}
          body: |
            Boost: [${{steps.build.outputs.BOOST_VERSION}}](https://github.com/boostorg/boost/tree/${{steps.build.outputs.BOOST_VERSION}})
            ICU: [${{steps.build.outputs.ICU_VERSION}}](https://github.com/unicode-org/icu/tree/${{steps.build.outputs.ICU_VERSION}})
          files: |
            ${{steps.build.outputs.DIST_NAME}}.zip
            ${{steps.build.outputs.DIST_NAME}}.zip.sha1
            ${{steps.build.outputs.DIST_NAME}}.tar.gz
            ${{steps.build.outputs.DIST_NAME}}.tar.gz.sha1
