# Copyright (c) 2022 github.com/System233
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT
name: Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        android_abi: [armeabi-v7a,arm64-v8a,x86,x86_64]
        android_platform: [34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19]
        type: [shared,static]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        id: build
        run: |
          ANDROID_ABI=${{matrix.android_abi}}
          ANDROID_PLATFORM=${{matrix.android_platform}}
          BUILD_TYPE=${{matrix.type}}
          BOOST_VERSION=$(./latest-boost-version.sh)
          ICU_VERSION=$(./latest-icu-version.sh)
          ICU_NAME=$(echo $ICU_VERSION|grep --perl-regex -e "release-\\K(.*)"  --only-matching|sed -e "s/-/./g")
          BOOST_DIST_NAME=$BOOST_VERSION-icu$ICU_NAME-android$ANDROID_PLATFORM-$ANDROID_ABI-$BUILD_TYPE.zip
          
          echo "{name}={$BOOST_VERSION}" >> $GITHUB_OUTPUT
          echo "{zip}={$BOOST_DIST_NAME}" >> $GITHUB_OUTPUT
          echo $BOOST_VERSION $ICU_VERSION
          ./build.sh $ANDROID_ABI $ANDROID_PLATFORM $BOOST_VERSION $ICU_VERSION $BUILD_TYPE
      - name: Archive
        run: |
          cd dist
          zip -9 ../${{steps.build.outputs.zip}} -r . 
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{steps.build.outputs.name}}
          tag_name: ${{steps.build.outputs.name}}
          files: |
            ${{steps.build.outputs.zip}}